name: Daily Main Script

on:
  schedule:
    - cron: '0 5 * * *'  # 8 AM IDT (UTC+3)
  workflow_dispatch:      # Enables manual run from GitHub UI

jobs:
  run-main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'  # Adjust to your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install requests==2.32.4 spotipy==2.25.1

      - name: Run main.py
        run: python main.py
